[project]
name = "vimania_uri_rs"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "sysid", email = "sysid@gmx.de" }
]
readme = "README.md"
requires-python = ">= 3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
]

#[build-system]
#requires = ["hatchling"]
#build-backend = "hatchling.build"
[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[tool.rye]
managed = true
dev-dependencies = [
    "maturin-import-hook>=0.1.0",
    "pip>=24.2",
    "pytest>=8.3.2",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["py"]
