name: Test and Quality Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
#        python-version: ["3.10", "3.11", "3.12", "3.13"]
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install maturin
        run: pip install maturin

      - name: Install dependencies
        run: |
          uv sync
          uv run maturin develop

      - name: Run Python tests
        run: |
          PYTHONPATH=pythonx uv run pytest tests -v --tb=short

      - name: Run Rust tests
        run: cargo test --lib

      - name: Check Python formatting
        run: uv run ruff format --check pythonx/vimania_uri_ tests

      #- name: Check Python linting
      #  run: uv run ruff check pythonx/vimania_uri_ tests

      #- name: Run mypy
      #  run: uv run mypy --config-file pyproject.toml --install-types --non-interactive pythonx/vimania_uri_

      - name: Check Rust formatting
        run: cargo fmt --check

      #- name: Run Rust linting
      #  run: cargo clippy -- -D warnings

      - name: Check Rust compilation
        run: cargo check

      - name: Audit Rust dependencies
        run: |
          cargo install cargo-audit
          cargo audit